remote_theme: b2a3e8/jekyll-theme-console

title: man -s 7 ideas

header_pages:
  - index.md
  - about.md

style: hacker # dark (default), light or hacker
listen_for_clients_preferred_style: false # false (default) or true

footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'

#google_analytics: UA-NNNNNNNN-N
